### ISSUE TITLE
Project under test (and dependencies) not found for test project

### ISSUE THREAD

**Issue by stefanodacchille** [novoda/gradle-android-test-plugin#2]
Building the project often - but not always - fails because the compilation phase of the tests fails. This happens because the dependencies to the main project cannot be resolved. If I rerun gradle a couple of times - cleaning the workspace - the problem disappears. The issue seems more likely to happen when something in the main project changes. I noticed the problem first when I was working on the RoboSpock sample application, but it happens in another project I'm currently working on. Do you guys have the same issue?

**Comment by blundell** [comment]
Legacy issue, please re-open if you still have fault
