### ISSUE TITLE
Trouble following instructions

### ISSUE THREAD

**Issue by westonized** [novoda/gradle-android-test-plugin#31]
I've followed instructions the best I can and on `./gradlew test` from the project dir I get:

    A problem occurred evaluating project ':testslib'.
    > Could not find property 'processManifest' on com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated@3380ca3d.

I've clearly messed up the instructions.

Would appreciate either help or recommendation of a project that uses it I can inspect.

So I have:

Project:
===

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:1.0.0'
            classpath 'com.novoda:gradle-android-test-plugin:0.9.9'
        }
    }
    
    allprojects {
        repositories {
            jcenter()
        }
    }

app:
===

    apply plugin: 'com.android.application'
    
    android {
        compileSdkVersion 21
        buildToolsVersion "21.1.2"
    
        defaultConfig {
            applicationId "com.example.evansa.novodorobolectricexample"
            minSdkVersion 21
            targetSdkVersion 21
            versionCode 1
            versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }
    
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
    }

testslib:
===

    apply plugin: 'java'
    apply plugin: 'android-test'
    
    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.11'
        testCompile 'org.mockito:mockito-core:1.9.5'
        testCompile 'com.squareup:fest-android:1.0.+'
        testCompile 'org.robolectric:robolectric:2.1.+'
    }
    
    android {
        projectUnderTest ':app'
    }

**Comment by xrigau** [comment]
Try using the latest version of the plugin `0.10.1`

**Comment by blundell** [comment]
no reply since january, closing since we just released `0.10.4`
