### ISSUE TITLE
ApplicationId different from Package name

### ISSUE THREAD

**Issue by joninvski** [novoda/gradle-android-test-plugin#35]
On my App the applicationId is different from the packageId

Because of this when I run the test task it fails because the resource files are not found.

If I change the defaultConfig applicationId to be equal to the packageId the unit test work pass.

**Comment by blundell** [comment]
nice bug! :+1:

**Comment by joninvski** [comment]
A workaround is to change the packageName in the robolectric runner:

Just extend the default RobolectricTestRunner and then change the package name like this:

    @Override
    protected AndroidManifest getAppManifest(Config config) {

      AndroidManifest manifest = super.getAppManifest(config);
      manifest.setPackageName("your.package.namespace");

      return manifest;
    }

Then use the Custom Robolectric Runner in your tests

**Comment by blundell** [comment]
looks like a change outside of this plugin is a better solution :+1:
